# Setup
title:               Ali Rana
tagline:             'Analytics and Innovation'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
# url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ali Rana
  url:               https://twitter.com/ranaalisaeed
  email:             alirana@engineer.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

# My specific setup
include:
  - _pages

collections_dir: my_collections
collections:
  projects:
    output: true