# Setup
title: Ali Rana
tagline: "Project, Analytics, Innovation"
description: 'Portfolio and Blog about analytics, technology and stuff that interest me. Made with <a href="https://jekyllrb.com" target="_blank">Jekyll</a>.'
url: "https://ranaalisaeed.github.io" # removed https://ranaalisaeed.github.io to troubleshoot form submission
baseurl: "" # needed to generate favicon URL
paginate: 5
permalink: pretty
excerpt_separator: <!--more-->

# About/contact
author:
  name: Ali Rana
  url: https://twitter.com/ranaalisaeed
  email: alirana@engineer.com

seo:
  description: "Ali Rana's portfolio showcasing projects in project management, analytics, and innovation"
  image: /public/images/profile-pictures/profile.jpg
  twitter:
    username: ranaalisaeed
  social:
    name: Ali Rana
    links:
      - https://twitter.com/ranaalisaeed
      - https://www.linkedin.com/in/alirana-tech

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y

# My specific setup
include:
  - _pages

collections_dir: my_collections
collections:
  projects:
    output: true

defaults:
  # Post defaults
  - scope:
      path: "my_collections/_posts"
      # type: posts
    values:
      layout: post
      comments: true
  - scope:
      path: "my_collections/_drafts"
      # type: drafts
    values:
      layout: post
      comments: true
  - scope:
      path: "my_collections/_projects"
      # type: drafts
    values:
      layout: project
      comments: false

exclude: ["extras", "CLAUDE.md"]
