# Site wide configuration

title: Rana Ali Saeed
locale: en_US
description: Data enthusiast, join me in my journey to master data skills!
logo: site-logo.jpg
search: true
# url: http://localhost:4000
url: https://ranaalisaeed.github.io

# Jekyll configuration

permalink:   /:categories/:title/ # or pretty
markdown:    kramdown # or rdiscount
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true
# pygments: true # after installing pygments
pageinate: 10 # not sure what this is

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Disqus comments
site:
  owner:
    disqus-shortname: ranaalisaeed-github-io

# Site owner
owner:
  name: Rana Ali Saeed
  avatar: bio-photo.jpg
  email: ali.saeedrana@gmail.com
  # disqus-shortname:
  twitter: #username
  facebook: #username
  github: ranaalisaeed
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: ranaalisaeed
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: ali.saeedrana@gmail.com
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
